---
- name: Setup Vpro bastion host
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
     - name: Import VPC setup variable
       include_vars: vars/bastion_setup

     - name: Import VPC setup variable
       include_vars: vars/output_vars_ids

     - name: Create vprofile ec2 key
       ec2_key:
         name: vprofile-key
         region: "{{region}}" 
       register: key_out 

     - name: Save a priv key into file bastion-key.pem
       copy:
         content: "{{key_out.key.private_key}}"
         dest: "./bastion-key.pem"
         mode: 0600
       when: key_out.changed

     - name: Create SG for bastion host
         ec2_group:
          name: Bastion-host-sg
          description: Allow port 22 for ssh
          region: "{{region}}"
          vpc_id: "{{vpcid}}"
          rules:
            - port: tcp 
              from_port: 22
              to_port: 22
              cidr_ip: "{{MYIP}}"     
         register: BastionSG-out

     - name: Creating the EC2 instance
       ec2:
         key_name: vprofile-key
         region: "{{region}}"
         instance_type: t2.micro
         image: "{{bastion_ami}}"
         wait: yes
         wait_timeout: 300
         instance_tags:
            Name: "Bastion_host"
            Project: Vprofile-vpc-setup
            Owner: Abhi
         exact_count: 1
         count_tags:
            Name: "Bastion_host"
            Project: Vprofile-vpc-setup
            Owner: Abhi
         group_id: "{{BastionSG-out.group_id}}"
         vpc_subnet_id: "{{pubsub1id}}"
       register: Bastionec2     
            
