- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
   - name: Import VPC Vars
     include_vars: var/vpc_setup

   - name: Create vpro VPC
     ec2_vpc_net:
       name: "{{vpc_name}}"
       cidr_block: "{{vpcCidr}}"
       region: "{{region}}"
       dns_support: yes
       dns_hostnames: yes
       tenancy: default
       state: "{{state}}"
     register: vpout   
